name: Deploy Label Printing App to Firebase

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for Angular
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 3: Install Angular CLI and dependencies
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm install --legacy-peer-deps
          echo "NPM installation completed"
      # Step 4: Build the Angular app
      - name: Build the Angular app
        run: |
          ng build
          echo "Build Completed"
      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase --version
          echo "Firebase version found"
          firebase use default
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
      - name: Deployment Completed
        run: echo "Firebase deployment Completed"
